export const organizers = [
  // {
  //   "email": "",
  //   "img": "ellie.png",
  //   "name": "Ellie Montemayor",
  //   "team": "Conference Co-Chair",
  //   "intro": "I'm Ellie Montemayor, majoring in Course 8 (Physics). I came to Cambridge from Bethesda, Maryland.",
  //   "position": "I'm one of this year's conference chairs, which basically means that I'm one of the four people who get a billion emails the week before the submission deadline from people who have questions about URTC, and am the self-professed most important member of the committee. I also just generally help do stuff in a lot of different aspects of the conference, from editing our website and working on day-of logistics to frantically emailing universities, potential sponsors, and other random people.",
  //   "interests": "I'm in love with all things wave physics! I love acoustic and radio engineering, and research work I've done involve thermoelectricity, can-tennas, and music in computers.",
  //   "spare_time": "I like to read weird, nerdy books and dusty old technical papers, make fun stuff like digital art on graphing calculators, and gradually wear away at my spare time by tacking on way too many commitments to my schedule.",
  //   "random": "Two random things about me: I don't know how to ride a bike, and I'm a massive Beatles fangirl."
  // },
  {
    "email": "lasyab@mit.edu",
    "img": "lasya.jpg",
    "name": "Lasya Balachandran",
    "team": "Conference Co-Chair",
    "intro": "I'm Lasya Balachandran, and I'm a senior double majoring in Course 6-2 (Electrical Engineering and Computer Science) and 18 (Mathematics). I'm from Marlboro, New Jersey.",
    "position": "I'm one of this year's conference chairs, so I work on aspects related to logistics, technology, sponsorship, and publicity, including helping to find speakers and panelists and working on the website. ", //"I'm on the logistics team, so I help out with reaching out to speakers and panelists, organizing events during the conference, and coordinating venues, including buildings/rooms and housing for in-person attendees and Hopin for virtual attendees.",
    "interests": "I'm interested in digital design, computer architecture, and embedded systems. I've recently done research related to developing a hardware accelerator for a graph-based vector search algorithm.",
    "spare_time": "I like to play tennis, ultimate frisbee, and basketball. I also enjoy running and hiking with friends.",
    "random": "I'm a twin, and I love grapes."
  },
  {
    "email": "jiew@mit.edu",
    "img": "jie.jpeg",
    "name": "Jie Wang",
    "team": "Conference Co-Chair",
    "intro": "I am a Postdoctoral Associate affiliated with the Department of Chemical Engineering",
    "position": "Co-chair",
    "interests": "science and technologies",
    "spare_time": "Tennis, cooking, concerts, movies, museum, etc.",
    "random": "(1) The US is the only country I have traveled to so far; (2) I have never tried roller coasters"
  },
  // {
  //   "email": "ggliu@mit.edu",
  //   "img": "george.jpg",
  //   "name": "George Liu",
  //   "team": "Conference Co-Chair",
  //   "intro": "I'm George Liu, majoring in 6-14 (Computer Science, Economics, and Data Science). I'm originally from Naperville, Illinois.",
  //   "position": "I'm one of this year's conference chairs, which (supposedly) means I have a lot of responsibility. It's also my first year as part of the URTC team, so much of my time has been spent doing the grunt work while the more experienced conference chairs actually plan the logistics.",
  //   "interests": "I'm most interested in computational social sciences. I've done some research so far at MIT, most of which pertains to public policy. ",
  //   "spare_time": "I play soccer, video games, and take naps. I wish I had something more interesting to say here.",
  //   "random": "I share a birthday (and birthplace) with Justin Bieber, and am very afraid of heights"
  // },
  // {
  //   "email": "",
  //   "img": "gianna.jpg",
  //   "name": "Gianna Torpey",
  //   "team": "Publicity Chair",
  //   "intro": "",
  //   "position": "",
  //   "interests": "",
  //   "spare_time": "",
  //   "random": ""
  // },

  {
    "email": "blin15@mit.edu",
    "img": "bobo.jpeg",
    "name": "Bobo Lin",
    "team": "Publicity & Marketing",
    "intro": "I'm Bobo, currently a freshman, and I intend to major in Course 18C (Mathematics with Computer Science). I'm from Chicago, Illinois.",
    "position": "I'm one of the publicity and marketing co-chairs, and am responsible for designing the logo and spreading information about the conference.",
    "interests": "I'm interested in the applications of math and computer science, especially in biology and medicine. I'm also interested in AI and its use in fields of computational biology and bioinformatics.",
    "spare_time": "In my spare time, I like taking walks around my neighborhood, get coffee and matcha, and reading new books.",
    "random": "1. I was born here in the states but raised in China. 2. My favorite drink from Dunkin is the cookie butter cold brew (highly recommend but sadly it's seasonal)."
  },
  {
    "email": "mamidala@mit.edu",
    "img": "srilekha.jpg",
    "name": "Srilekha Mamidala",
    "team": "Publicity & Marketing",
    "intro": "I'm Srilekha Mamidala, and I'm a freshman interested in majoring in Course 6-14 (CS and Economics). I'm originally from Garnet Valley, Pennsylvania.",
    "position": "I'm Publicity and Marketing Chair, which means I'm responsible for spreading awareness about the conference to make sure it's bigger than ever! From creating digital materials for sponsorships and communicating to interested presenters, it's my job to ensure URTC invites an exciting diversity of research.",
    "interests": "I'm interested in using computer science approaches to solve issues in the environmental and human health sectors. Recently, I've also done research applying principles from LLMs (like ChatGPT!) in the legal analytics sector. I'm also focused on taking research beyond the lab and into the hands of communities with entrepreneurship.",
    "spare_time": "I am a classical dancer and have been dancing for 11 years! I also enjoy landscape painting, love visiting new places.",
    "random": "I've never liked potato chips, and my dream city to visit is Tokyo."
  },
  {
    "email": "hanngao@mit.edu",
    "img": "hannah.jpg",
    "name": "Hannah Gao",
    "team": "Logistics",
    "intro": "I'm Hannah Gao, a sophomore majoring in 6-3. I am from Philadelphia, PA.",
    "position": "As one of the logistics chairs, I plan and recruit for conference events such as guest speakers and panel sessions, and I make sure these events run smoothly!",
    "interests": "All things AI; theoretical computer science",
    "spare_time": "Some of my hobbies include playing guitar, tennis, and frisbee.",
    "random": "1) Currently, my favorite flavor of ice cream is black sesame. 2) I love 90+ degree weather."
  },
  {
    "email": "adarsh@mit.edu",
    "img": "adarsh.jpeg",
    "name": "Adarsh Iyer",
    "team": "Logistics",
    "intro": "I'm a first-year from San Jose, California, intending to major in Course 6-9 (Computation and Cognition).",
    "position": "I handle logistics related to finding and coordinating with speakers and panelists as well as organizing special events at the conference.",
    "interests": "I am fascinated by brain-inspired (neural) computing, dynamical systems, computer graphics, computer vision, and symbolic deep learning. I've done some research work in these areas.",
    "spare_time": "As a member of the MIT Cross Country and Track teams, you'll usually find me running in my spare time. I also enjoy music composition, piano playing, 3D animation, carpentry, cooking, baking, reading, and making new friends.",
    "random": "I once ran six miles in flip-flops and I like gnocchi."
  },
  {
    "email": "disaac@mit.edu",
    "img": "dylan.jpg",
    "name": "Dylan Isaac",
    "team": "Sponsorship Chair",
    "intro": "I'm interested in everything relating to computation. I love learning more about the algorithms and mathematics in computer science that push our world forward. I also enjoy learning about the microscopic hardware in our machines.",
    "position": "I'm this year's sponsorship chair. In general, my goal is to secure funding and connections for this year's event and future events. ",
    "interests": "I am fascinated by brain-inspired (neural) computing, dynamical systems, computer graphics, computer vision, and symbolic deep learning. I've done some research work in these areas.",
    "spare_time": "Outside of academics, I enjoy ice skating, bicycling, and movie nights. You'll usually find me biking in a random place in Boston, falling on ice in MIT's ice rink, or hanging out with friends in Next House.",
    "random": "1) I'll eat anything sushi-shaped. 2) I've climbed two glaciers."
  },
  // {
  //   "email": "huangq@mit.edu",
  //   "name": "Qiong Zhou Huang",
  //   "img": "qiong.jpg",
  //   "team": "Technology Chair",
  //   "intro": "I'm Qiong Zhou Huang, majoring in Electrical Engineering and Computer Science. I'm from Brooklyn, New York. 🗽",
  //   "position": "As tech chair 🪑, I work on the magical technology that makes this website and other parts of the conference run.",
  //   "interests": "",
  //   "spare_time": "",
  //   "random": ""
  // },
  // {
  //   "email": "robertcc@mit.edu",
  //   "img": "robert.jpg",
  //   "name": "Robert Chen",
  //   "team": "Technology",
  //   "intro": "My name is Robert Chen, and I'm a Course 6 (Computer Science) major from Lexington, Massachusetts.",
  //   "position": "I'm on the technology team, so I help out with the website and other tech-related aspects of the conference.",
  //   "interests": "I'm interested in algorithms, machine learning, and finance. I have done research in computational psycholinguistics and applied cryptography.",
  //   "spare_time": "I'm a risk-averse adventurer who enjoys hiking and bouldering, horror movie enthusiast, chess beginner, and closeted weeb.",
  //   "random": "I'm on a mission to try every Mountain Dew flavor, and my favorite movie character is Megamind."
  // },
  // {
  //   "email": "",
  //   "img": "karen.jpg",
  //   "name": "Karen Liberman",
  //   "team": "Technology",
  //   "intro": "",
  //   "position": "",
  //   "interests": "",
  //   "spare_time": "",
  //   "random": ""
  // },
  // {
  //   "email": "cyung@mit.edu",
  //   "img": "cathy.jpg",
  //   "name": "Cathy Yung",
  //   "team": "Logistics Chair",
  //   "intro": "I'm Cathy Yung, currently majoring in Course 18C (Mathematics with Computer Science). I am from Germantown, Maryland!",
  //   "position": "I am one of the logistic chairs, so essentially, I help make sure the conference runs super smoothly. From reaching out to speakers, to organizing panel sessions, to time scheduling, I am responsible for making sure all these happen. My position also includes coordinating the venue (and in COVID years, the virtual technology) needed for the conference.",
  //   "interests": "Recently, I've been pretty into technology used for assisting people who are disabled. For example, people who have been paralyzed can use technology that tracks their eye movement to communicate with others and move around independently.",
  //   "spare_time": "I enjoy playing volleyball and tennis with my friends, as well as planning day trips + vacations. I'm also currently learning how to play guitar.",
  //   "random": "1. I sneeze when I look at the sun. 2. I hate balsamic vinegar."
  // },
  // {
  //   "email": "",
  //   "img": "lucas.jpg",
  //   "name": "Lucas Chu",
  //   "team": "Logistics",
  //   "intro": "",
  //   "position": "",
  //   "interests": "",
  //   "spare_time": "",
  //   "random": ""
  // },
  // {
  //   "email": "tammyc@mit.edu",
  //   "name": "Tammy Chen",
  //   "img": "tammy.jpeg",
  //   "team": "Advisor",
  //   "intro": "I'm Tammy Chen, majoring in 6-14. I came to MIT from Brooklyn, New York.",
  //   "position": "", //"I am one of this year's conference chairs which means I make sure the conference goes smoothly behind the scene. I am responsible for overseeing the different departments in URTC (logistics, technology, sponsorship, publicity) & conference planning on a large scale.",
  //   "interests": "I love learning more about artificial intelligence & investigating more into the virtual reality realm.",
  //   "spare_time": "I am a culprit of investing too much time into fantasy sports & analytics (particularly football and basketball) + playing Valorant. I also love taking long walks & visiting new places.",
  //   "random": "Chicken nuggets with guacamole is a superior food combination + I am beyond scared of heights."
  // },
  // {
  //   "email": "",
  //   "img": "ritik.jpeg",
  //   "name": "Ritik Patnaik",
  //   "team": "Advisor",
  //   "intro": "My name is Ritik Patnaik, a senior majoring in Course 6-2 (EECS). I’m originally from Plano, Texas.",
  //   "position": "I’m an advisor for this year’s conference. I am supporting the co-chairs as we transition back in to our in-person event, providing a knowledge base of how the conference was run pre-pandemic. This is my fourth year helping organize the event, after co-chairing the virtual conference last year with Meenu. This is my fifth year being involved in URTC as I presented at the conference during my senior year of high school.",
  //   "interests": "I love the embedded system and IOT technology space! I love seeing the applications microcontrollers and sensors have in all parts of our lives. PCB design is an art!",
  //   "spare_time": "I enjoy playing recreational sports, listening to music during my endurance runs, and spending time near/in water (preferably clean bodies of water!)",
  //   "random": "I enjoy watching Bollywood movies and I’ve met the owner of the Cowboys, Jerry Jones."
  // },
  // {
  //   "email": "",
  //   "img": "meenu.jpg",
  //   "name": "Meenu Singh",
  //   "team": "Advisor",
  //   "intro": "",
  //   "position": "",
  //   "interests": "",
  //   "spare_time": "",
  //   "random": ""
  // },
]
