export const speakers = [
{
    name: 'Prof. Ali Abedi',
    affiliation: 'University of Maine',
    img: 'ali.jpeg',
    type: 'Keynote',
    title: 'Digital Radio Intelligent Forest Twin (DRIFT)',
    abstact: 'Forest ecosystem plays a major role in determining the future climate. We need to monitor the forest environment to learn how stressors affect the changes over time. The concept of digital twins and parallel intelligence can be a powerful tool to create a digital replica of a forested land in the cloud with real time connections to the physical forest using radio frequency identification tags and sensors. This is an ambitious goal which requires a significant number of sensors which are low cost, reliable and power efficient. We also require extremely efficient spectrum sharing strategies to make this network economical, while not interfering with other existing networks. In this talk, we will take a deeper look at deep learning and artificial intelligence to learn how a digital forest twin can operate using a radio intelligent system. If you are interested to learn about wireless sensing, networking, and AI you will find this talk interesting. The main goal of this research is to predict abrupt or extreme events as well as slow changes in the climate and help develop data driven forest management plans and policies.',
    bio: 'Ali Abedi received his BSEE and MSEE from Sharif University in 1996 and 1998, and his PhD in Electrical and Computer Engineering, from University of Waterloo in 2004. Dr. Abedi joined the University of Maine, Orono in 2005, where he is currently Professor of Electrical and Computer Engineering and Associate Vice President for Research at UMaine, an R1 Classified Institution by Carnegie foundation. He was visiting Associate Professor at the University of Maryland, College Park, MD and Guest Researcher at NIST in 2012 and Faculty Fellow at NASA in 2016. Dr. Abedi is founding Director of WiSe-Net Lab where he directs research programs in wireless communications and sensor networks for structural monitoring, space explorations and bio-medical applications. Dr. Abedi has completed 60+ funded research grants worth over $34M resulting in 115+ publications with over 44,000+ downloads and 1000+ citations. He is the recipient of several IEEE awards and served as Associate Editor from multiple IEEE journals, and chair for several IEEE conferences. He is 2022 Vice President for Conferences at IEEE Council on Radio Frequency Identification.',
},
{
    name: 'Sreeram (Ram) Dhurjaty, PhD, LSMIEEE',
    affiliation: '',
    img: 'sreeram.jpeg',
    type: 'Keynote',
    title: 'Inventions and innovations that matter to Humanity',
    abstact: 'Many inventors invent for the sake of increasing their patent-portfolio. Often, these inventions expire without bringing any or scant utility to humanity. Invention, according to patent offices refers to something that is novel and illustrates a method or process that was hitherto unknown. The method, is not necessarily useful and may often be just a novelty. An example of this is an automated, battery-operated fly-swatter.    Inventions or innovations that matter, are those that could be game-changers for humanity or meet a pressing, immediate, need, such as ventilators and oxygen concentrators to meet the needs of a pandemic Often, their importance becomes obvious over time. For example, when the laser was invented in the early 60’s it was looked upon as a novelty. Now, there is no doubt that lasers are ubiquitous in our everyday life. Similarly, when CT scanners were, first invented there were pronouncements that the city of NY, during the late 60s required one or two CT scanners. Today, CT scanners are ubiquitous Another recent example is the digital retrofittable digital radiology detector, which replaced screen-film systems, seamlessly, by converting existing radiology suites to Digital, which would have otherwise cost hundreds of thousands of dollars. This invention did not modify the workflow of the Radiology-Technologist but instead obsoleted noxious chemical processors, which were used to develop film. Innovations are not, necessarily, inventions in the parlance of the patent office if there is “obviousness” in the modification of a previously patented work. However, that does not imply that the innovation is not useful. Often, an older patent may have methods that may have been impractical, when it was published, due to limited processing power available at that time, but may have broad claims that could be relevant with faster processors. The invention may have languished, or expired, after many years, waiting for faster processors, to make the invention practical. The use of the faster processors could be classified as innovation, which could lead to other patents that stand on the shoulder of older inventions.',
    bio: 'Ram held senior positions in engineering and research, in medical systems, at Eastman Kodak Company, Analogic, and Bose Corporation before embarking on a career of full time consulting. He was educated at IIT Bombay and Yale University and has degrees in Civil Engineering, Fluid mechanics, Electronic Instrumentation, Biomedical Engineering, and Control System Theory. Over his career he has designed medical systems such as Patient Monitors, Defibrillators, CT scanners, Fetal Monitoring systems, Digital and Computed Radiography, and Telemedicine. He has written standards for ECG systems and Defibrillators for AAMI. He was the past chair of the IEEE, Rochester NY section. Ram has consulted for Universities as well as Industry, including some fortune 100 companies. His consulting includes Strategic-Technology Consulting, Designing and implementing research systems for Universities, System design and implementation for the Medical device industry. His consulting includes precision Analog circuitry, High Voltage Power supplies and Magnetics for X-Ray systems. He has 16 issued patents in areas of medical devices and systems. His significant Inventions include a Hand-Cranked defibrillator and the retrofittable Digital Radiography system. Ram is a mentor to several startups in the Rochester, NY area and is also involved in STEM science fairs. He likes working with young people. Ram is a Life senior member of the IEEE, Emeritus member of AAPM, member of AHA and member of SPIE',
},
{
    name: 'More Speakers',
    affiliation: 'More Speakers and Panelists will be announced soon!',
    img: 'default.jpg',
    Info: 'More Speakers and Panelists will be announced soon!'
}
]